name: Build Unsigned Windows Linux and macOS

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug VS install
        run: |
          & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -format json
        shell: pwsh

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Configure Windows build
        run: cmake -S . -B build/windows -G "Visual Studio 17 2022" -A x64

      - name: Build Windows app
        run: cmake --build build/windows --config Release --target suspend

      - name: Upload Unsigned EXE to Artifacts
        uses: actions/upload-artifact@v4
        with: 
          path: build/windows/Release/suspend.exe
          name: suspend.exe
